from pandas.api.types import CategoricalDtype


pos_categorical_dtypes = {
    'syntactic category': CategoricalDtype(['noun', 'verb', 'adjective', 'adverb', 'function word', 'cardinal number', '.'], ordered=True),
}

pos_mappings = {
    'POS tag': {
        "''": ".",
        ",": ".",
        "-LRB-": ".",
        ".": ".",
        ":": ".",
        "ADD": "UH",
        "CC": "CC",
        "CD": "CD",
        "DT": "DT",
        "EX": "EX",
        "FW": "UH",
        "GW": "UH",
        "HYPH": ".",
        "IN": "IN",
        "JJ": "JJ",
        "JJR": "JJR",
        "JJS": "JJS",
        "LS": ".",
        "MD": "MD",
        "NFP": "UH",
        "NN": "NN",
        "NNP": "NNP",
        "NNPS": "NNS",
        "NNS": "NNS",
        "PDT": "PDT",
        "POS": "POS",
        "PRP": "PRP",
        "PRP$": "PRP$",
        "RB": "RB",
        "RBR": "RBR",
        "RBS": "RBS",
        "RP": "RP",
        "SYM": ".",
        "TO": "TO",
        "UH": "UH",
        "VB": "VB",
        "VBD": "VBD",
        "VBG": "VBG",
        "VBN": "VBN",
        "VBP": "VBP",
        "VBZ": "VBZ",
        "WDT": "WDT",
        "WP": "WP",
        "WP$": "WP$",
        "WRB": "WRB",
        "``": ".",
    },
    'POS tag (compressed)': {
        "''": ".",
        ",": ".",
        "-LRB-": ".",
        ".": ".",
        ":": ".",
        "ADD": "UH",
        "CC": "CC",
        "CD": "CD",
        "DT": "DT",
        "EX": "PRP",
        "FW": "UH",
        "GW": "UH",
        "HYPH": ".",
        "IN": "IN",
        "JJ": "adjective",
        "JJR": "adjective",
        "JJS": "adjective",
        "LS": ".",
        "MD": "MD",
        "NFP": "UH",
        "NN": "noun",
        "NNP": "noun",
        "NNPS": "noun",
        "NNS": "noun",
        "PDT": "DT",
        "POS": "POS",
        "PRP": "PRP",
        "PRP$": "PRP",
        "RB": "adverb",
        "RBR": "adverb",
        "RBS": "adverb",
        "RP": "RP",
        "SYM": ".",
        "TO": "TO",
        "UH": "UH",
        "VB": "verb",
        "VBD": "verb",
        "VBG": "verb",
        "VBN": "verb",
        "VBP": "verb",
        "VBZ": "verb",
        "WDT": "wh-word",
        "WP": "wh-word",
        "WP$": "wh-word",
        "WRB": "wh-word",
        "``": ".",
    },
    'syntactic category': {
        "''": ".",
        ",": ".",
        "-LRB-": ".",
        ".": ".",
        ":": ".",
        "ADD": ".",
        "CC": "function word",
        "CD": "cardinal number",
        "DT": "function word",
        "EX": "function word",
        "FW": ".",
        "GW": ".",
        "HYPH": ".",
        "IN": "function word",
        "JJ": "adjective",
        "JJR": "adjective",
        "JJS": "adjective",
        "LS": ".",
        "MD": "function word",
        "NFP": ".",
        "NN": "noun",
        "NNP": "noun",
        "NNPS": "noun",
        "NNS": "noun",
        "PDT": "function word",
        "POS": "function word",
        "PRP": "function word",
        "PRP$": "function word",
        "RB": "adverb",
        "RBR": "adverb",
        "RBS": "adverb",
        "RP": "function word",
        "SYM": ".",
        "TO": "function word",
        "UH": ".",
        "VB": "verb",
        "VBD": "verb",
        "VBG": "verb",
        "VBN": "verb",
        "VBP": "verb",
        "VBZ": "verb",
        "WDT": "function word",
        "WP": "function word",
        "WP$": "function word",
        "WRB": "function word",
        "``": ".",
    },
}

pos_palette = {
    "''": "black",
    "``": "black",
    ",": "black",
    ".": "black",
    ":": "black",
    ".": "black",
    "-LRB-": "black",
    "HYPH": "black",
    "LS": "black",
    "SYM": "black",
    "CC": "brown",
    "cardinal number": "tab:gray",
    "CD": "tab:gray",
    "DT": "salmon",
    "EX": "rosybrown",
    "function word": "tab:purple",
    "IN": "tab:purple",
    "adjective": "tab:orange",
    "JJ": "tab:orange",
    "JJR": "gold",
    "JJS": "yellow",
    "MD": "rosybrown",
    "noun": "tab:blue",
    "NN": "tab:blue",
    "NNP": "navy",
    "NNS": "cadetblue",
    "PDT": "saddlebrown",
    "POS": "grey",
    "PRP": "tab:olive",
    "PRP$": "olivedrab",
    "adverb": "tab:pink",
    "RB": "tab:pink",
    "RBR": "magenta",
    "RBS": "palevioletred",
    "RP": "darkviolet",
    "TO": "indigo",
    "ADD": "tab:green",
    "FW": "tab:green",
    "GW": "tab:green",
    "NFP": "tab:green",
    "UH": "tab:green",
    "verb": "tab:red",
    "VB": "tab:red",
    "VBD": "salmon",
    "VBG": "orangered",
    "VBN": "chocolate",
    "VBP": "pink",
    "VBZ": "crimson",
    "WDT": "darkcyan",
    "WP": "slateblue",
    "WP$": "darkslateblue",
    "wh-word": "tab:cyan",
    "WRB": "tab:cyan",
}
