grids = [
    {
        "main_file": ["train"],
        "dataset": ["saycam"],
        "lambda_mm": [0.],
        "lambda_lm": [1.],
        "captioning": [False, True],
        "sim": ["mean"],
        "embedding_type": ["flat"],
        "text_encoder": ["lstm"],
        "embedding_dim": [512],
        "tie": ["True"],
        "bias": ["True"],
        "crange": [1],
        "dropout_i": [.5],
        "dropout_o": [.0],
        "pretrained_cnn": [True],
        #"cnn_model": ["resnext50_32x4d"],
        "multiple_frames": [True],
        "augment_frames": [True],
        "normalize_features": [True],
        "gpus": [1],
        "num_workers": [4],
        "batch_size": [8],
        "drop_last": [True],
        "optimizer": ["AdamW"],
        "lr": [0.003],
        "lr_scheduler": [True],
        "patience": [10],
        "weight_decay": [0.05],
        "val_batch_size": [16],
        "eval_include_sos_eos": [True],
        "seed": [0],
        "optimize_unused": [True],
        "eval_textgen": [False],
        "max_epochs": [100],
        "check_val_every_n_epoch": [1],
        "beam_width": [3],
        "checkpoint_callback": ["True"],
        "logger": ["True"]
    },
    {
        "main_file": ["train"],
        "dataset": ["saycam"],
        "lambda_mm": [0.],
        "lambda_lm": [1.],
        "captioning": [False, True],
        "sim": ["mean"],
        "embedding_type": ["flat"],
        "text_encoder": ["lstm"],
        "embedding_dim": [512],
        "tie": ["True"],
        "bias": ["True"],
        "crange": [1],
        "dropout_i": [.5],
        "dropout_o": [.0],
        "pretrained_cnn": [True],
        #"cnn_model": ["resnext50_32x4d"],
        "multiple_frames": [True],
        "augment_frames": [True],
        "normalize_features": [True],
        "gpus": [1],
        "num_workers": [4],
        "batch_size": [512],
        "drop_last": [True],
        "optimizer": ["AdamW"],
        "lr": [0.03],
        "lr_scheduler": [True],
        "patience": [2],
        "weight_decay": [0.05],
        "val_batch_size": [16],
        "eval_include_sos_eos": [True],
        "seed": [0],
        "optimize_unused": [True],
        "eval_textgen": [False],
        "max_epochs": [100],
        "check_val_every_n_epoch": [1],
        "beam_width": [3],
        "checkpoint_callback": ["True"],
        "logger": ["True"]
    },
]
# ordered flags to display in jobname
flags = [
    "dataset", "captioning",
    #"cnn_model",
    "text_encoder", "embedding_dim",
    #"tie", "bias",
    #"dropout_i", "dropout_o",
    "batch_size", "lr", "lr_scheduler", "patience", "weight_decay", "eval_include_sos_eos", "seed",
]
