grids = [
    {
        "main_file": ["train"],
        "dataset": ["saycam"],
        "lambda_mm": [.5],
        "lambda_lm": [.5],
        "captioning": [False],
        "sim": ["mean"],
        "embedding_type": ["flat"],
        "text_encoder": ["lstm"],
        "embedding_dim": [512],
        "tie": ["True"],
        "bias": ["True"],
        "crange": [1],
        "dropout_i": [.5],
        "dropout_o": [.0],
        "pretrained_cnn": [True],
        "multiple_frames": [True],
        "augment_frames": [True],
        "normalize_features": [True],
        "fix_temperature": [True],
        "temperature": [0.1],
        "gpus": [1],
        "num_workers": [8],
        "batch_size": [16],
        "drop_last": [True],
        "optimizer": ["AdamW"],
        "lr": [0.006],
        "lr_scheduler": [True],
        "weight_decay": [0.04],
        "val_batch_size": [16],
        "eval_include_sos_eos": [True],
        "seed": [0, 1, 2][:1],
        "optimize_unused": [True],
        "max_epochs": [200],
        "checkpoint_callback": ["True"],
        "logger": ["True"]
    },
    {
        "main_file": ["train"],
        "dataset": ["saycam"],
        "lambda_mm": [.5],
        "lambda_lm": [.5],
        "captioning": [False],
        "sim": ["mean"],
        "embedding_type": ["flat"],
        "text_encoder": ["lstm"],
        "embedding_dim": [512],
        "tie": ["True"],
        "bias": ["True"],
        "crange": [1],
        "dropout_i": [.5],
        "dropout_o": [.0],
        "pretrained_cnn": [True],
        "multiple_frames": [True],
        "augment_frames": [True],
        "normalize_features": [True],
        "fix_temperature": [True],
        "temperature": [0.1],
        "gpus": [1],
        "num_workers": [8],
        "batch_size": [512],
        "drop_last": [True],
        "optimizer": ["AdamW"],
        "lr": [0.01],
        "lr_scheduler": [True],
        "weight_decay": [0.05],
        "val_batch_size": [16],
        "eval_include_sos_eos": [True],
        "seed": [0, 1, 2][:1],
        "optimize_unused": [True],
        "max_epochs": [200],
        "checkpoint_callback": ["True"],
        "logger": ["True"]
    },
]
# ordered flags to display in jobname
flags = [
    "dataset", #"captioning",
    #"cnn_model",
    "lambda_mm", "lambda_lm",
    "sim", "embedding_type",
    "text_encoder", "embedding_dim",
    #"dropout_i", "dropout_o",
    #"fix_temperature", "temperature",
    "batch_size", "optimizer", "lr", "lr_scheduler", "weight_decay", "val_batch_size", "eval_include_sos_eos", "seed",
]
