grids = [
    {
        "main_file": ["train"],
        "dataset": ["saycam"],
        "lambda_mm": [0.],
        "lambda_lm": [1.],
        "captioning": [False],
        "sim": ["mean"],
        "embedding_type": ["spatial"],
        "text_encoder": ["cbow"],
        "embedding_dim": [512],
        "tie": ["False"],
        "bias": ["False"],
        "crange": [1],
        "dropout_i": [.0],
        "dropout_o": [.1],
        "pretrained_cnn": [True],
        "multiple_frames": [True],
        "augment_frames": [True],
        "normalize_features": [True],
        "gpus": [1],
        "num_workers": [4],
        "batch_size": [8],
        "drop_last": [True],
        "optimizer": ["AdamW"],
        "lr": [0.0001],
        "lr_scheduler": [True],
        "patience": [2],
        "weight_decay": [0.03],
        "seed": [0],
        "optimize_unused": [True],
        "eval_textgen": [False],
        "max_epochs": [200],
        "check_val_every_n_epoch": [1],
        "beam_width": [3],
        "checkpoint_callback": ["True"],
        "logger": ["True"]
    },
    {
        "main_file": ["train"],
        "dataset": ["saycam"],
        "lambda_mm": [0.],
        "lambda_lm": [1.],
        "captioning": [False],
        "sim": ["mean"],
        "embedding_type": ["spatial"],
        "text_encoder": ["cbow"],
        "embedding_dim": [512],
        "tie": ["False"],
        "bias": ["False"],
        "crange": [1],
        "dropout_i": [.0],
        "dropout_o": [.1],
        "pretrained_cnn": [True],
        "multiple_frames": [True],
        "augment_frames": [True],
        "normalize_features": [True],
        "gpus": [1],
        "num_workers": [4],
        "batch_size": [512],
        "drop_last": [True],
        "optimizer": ["AdamW"],
        "lr": [0.001],
        "lr_scheduler": [True],
        "patience": [2],
        "weight_decay": [0.03],
        "seed": [0],
        "optimize_unused": [True],
        "eval_textgen": [False],
        "max_epochs": [30],
        "check_val_every_n_epoch": [1],
        "beam_width": [3],
        "checkpoint_callback": ["True"],
        "logger": ["True"]
    },
]
# ordered flags to display in jobname
flags = [
    "dataset", #"captioning",
    "text_encoder", "embedding_dim",
    "tie", "bias",
    "crange", "dropout_i", "dropout_o",
    "batch_size", "lr", "lr_scheduler", "patience", "weight_decay", "seed",
]
