grids = [
    {
        "main_file": ["train"],
        "dataset": ["saycam"],
        "lambda_mm": [1.],
        "lambda_lm": [0.],
        "captioning": [False],
        "sim": ["mean"],
        "embedding_type": ["flat"],
        "text_encoder": ["lstm"],
        "embedding_dim": [512],
        "tie": ["True"],
        "bias": ["True"],
        "crange": [1],
        "dropout_i": [.5],
        "dropout_o": [.0],
        "pretrained_cnn": [True],
        "multiple_frames": [True],
        "augment_frames": [True],
        "normalize_features": [True],
        "fix_temperature": [True],
        "temperature": [0.07],
        "gpus": [1],
        "num_workers": [8],
        "batch_size": [512],
        "drop_last": [True],
        "optimizer": ["AdamW"],
        "lr": [0.003],
        "lr_scheduler": [True],
        "weight_decay": [0.05],
        "val_batch_size": [16],
        "seed": [0],
        "optimize_unused": [True],
        "eval_textgen": [False],
        "max_epochs": [200],
        "check_val_every_n_epoch": [1],
        "beam_width": [3],
        "checkpoint_callback": ["True"],
        "logger": ["True"]
    },
]
# ordered flags to display in jobname
flags = [
    "dataset", #"captioning",
    "sim", "embedding_type",
    "text_encoder", "embedding_dim",
    #"dropout_i", "dropout_o",
    "fix_temperature", "temperature",
    "batch_size", "lr", "lr_scheduler", "weight_decay", "seed",
]
